name: Makefile CI

on:
  push:
    branches: [ "lineage-21" ]
  pull_request:
    branches: [ "lineage-21" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Make Kernel
      run: make OBJDUMP="aarch64-linux-gnu-objdump -d 2>/dev/null >/dev/null" ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CROSS_COMPILE_ARM32=arm-linux-gnuabeihf- CC=clang LD=ld.lld HOSTCC=clang HOSTLD=ld.lld O=out sagit_defconfig all -j64 

   
