name: Makefile CI

on:
  push:
    branches: [ "lineage-21" ]
  pull_request:
    branches: [ "lineage-21" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential
        
    - name: Configure kernel
      run: make sagit_defconfig

    - name: Build project
      run: |
        make

    - name: Run tests (optional)
      run: |
        make test

    - name: Upload artifact (optional)
      uses: actions/upload-artifact@v3
      with:
        name: build-output
        path: out
